
name: Build consrv for Raspberry Pi 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # 确保使用最新的 Go 版本

      - name: Install cross-compilation dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Build for Raspberry Pi 4 (ARM64)
        run: |
          export GOARCH=arm64
          export GOOS=linux
          export CC=aarch64-linux-gnu-gcc
          go build -o consrv-linux-arm64

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: consrv-linux-arm64
          path: consrv-linux-arm64
